spring:
  profiles: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/votacao
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:}
    password: ${DB_PASS:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enable: true
cpf:
  service:
    url: https://brasilapi.com.br/api/cpf/v1