app:
  kafka:
    enabled: true
    topic:
      votos: votos

spring:
  profiles: docker

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  datasource:
    url: jdbc:postgresql://postgres:5432/votacao
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:}
    password: ${DB_PASS:}
    hikari:
      maximum-pool-size: 50   # ajustável conforme carga
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  http:
    encoding:
      charset: UTF-8
      force: true
      enable: true

cpf:
  service:
    url: https://brasilapi.com.br/api/cpf/v1
