spring:
  datasource:
    url: jdbc:h2:mem:votacao;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enable: true
cpf:
  service:
    url: https://brasilapi.com.br/api/cpf/v1
