spring:
  profiles:
    active: ${profiles.active:dev}
  http:
    encoding:
      enable: true

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true

info:
  app:
    name: Votacao API
    version: 1.0.0
