spring:
  datasource:
    # H2 em modo arquivo, persiste em ./data/votacao-db.mv.db
    url: jdbc:h2:file:./data/votacao-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 50   # ajustável conforme carga
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enable: true

cpf:
  service:
    url: https://brasilapi.com.br/api/cpf/v1
